name: MusicFun Deploy

on:
  push:
    branches: [main] #v kakyi vetky pushim


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    # na kakoi sisteme budet start

    steps:
      - uses: actions/checkout@v4 #beret last changes
      - uses: actions/setup-node@v4 #install nodejs 
        with:
          node-version: 20 #node js imenno 20 version
      - run: npm install # npm install delaem v proect sozdaem nodes
      - run: npm run build # sozdaem build 4tob poyavilsya dist
      - uses: actions/upload-pages-artifact@v3 # artifact - eto papka dist kotoraya sozdalas
        with:
          path: dist #obozna4aem 4to papka dist eto artifact
      - uses: actions/deploy-pages@v4 #zdeploy artifact na prod
